name: Register Module Preview

on:
  workflow_call:
    inputs:
      module_dirs:
        required: true
        type: string
        description: 'List of unique changed directories'
    secrets:
      username:
        required: true
        description: 'Facets control plane username'
      token:
        required: true
        description: 'Facets control plane token (stored as a secret)'
      control_plane_url:
        required: true
        description: 'Facets control plane URL'

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2  # Fetch the last two commits

      - name: Get Unique Changed Directories and register the module directory as preview
        run: |
          set -e

          # Use the provided changed_dirs input
          IFS=' ' read -r -a dirs <<< "${{ inputs.module_dirs }}"

          # Loop through the unique directories and check for facets.yaml
          echo "Unique changed directories:" 
          for dir in "${dirs[@]}"; do
            echo "$dir"
            if [[ -f "$dir/facets.yaml" ]]; then
              # Register the module as preview
              curl -s https://facets-cloud.github.io/facets-schemas/scripts/module_register.sh | bash -s -- -c ${{ secrets.control_plane_url }} -u ${{ secrets.username }} -t ${{ secrets.token }} -p "$dir"
            else
              echo "No facets.yaml found in $dir"
            fi
          done
